knowledge_graph:
  path: "knowledgegraph/data/emotions.owl"

logging:
  level: "INFO"

experiment:
  repeats: 20

models:
  openai:
    model: "gpt-4o"
    system_prompt:  "You are a commonsense knowledge engineer. Return **ONLY** valid JSON."